-- CreateTable
CREATE TABLE "STARTUPS" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "FOUNDED" TEXT NOT NULL,
    "INDUSTRY" TEXT DEFAULT 'Unknown',
    "FUNDING_AMOUNT" INTEGER,
    "INVESTOR" TEXT DEFAULT 'Unknown',
    "INVESTMENT_TYPE" TEXT DEFAULT 'Unknown',
    "CITY" TEXT DEFAULT 'Unknown'
);
